# -*- coding: utf-8 -*-
"""Hotel booking data set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwYWstynqAtXGM5G7U3LW2tLyxi3i6GH
"""

!pip install pandas
import pandas as pd
!pip install numpy
import numpy as np
!pip install seaborn
import seaborn as sns
!pip install matplotlib
import matplotlib.pyplot as plt

hb=pd.read_csv("/content/hotel_booking.csv")

hb.head(1)

hb.tail(1)

hb.info()

hb.count()

hb.shape

hb.describe()

sns.heatmap(hb.isnull(),yticklabels=False,cbar=False,cmap="tab20c_r")
plt.title("Missing data")
plt.show()

#showcasing the types of variables(columns)
hb.dtypes

#individual describing each columns same apply for all variables(columns).
hb["adults"].describe()

#duplicates
dhb=hb[hb.duplicated()]
print("Numbers of duplicated rows:",dhb.shape)

#identifying missing data
print(hb.isnull().sum())

#creating new data set of importent columns
fhb=hb[["hotel","is_canceled","arrival_date_year","arrival_date_month","adults","children","babies","country","meal","market_segment","distribution_channel","is_repeated_guest","assigned_room_type","deposit_type","customer_type","required_car_parking_spaces"]]

plt.figure(figsize=(8,8))
sns.countplot(x=fhb['meal'])
plt.show()

plt.figure(figsize=(8,8))
sns.countplot(x=fhb['arrival_date_year'])
plt.show()

plt.figure(figsize=(20,4))
sns.countplot(x=fhb['arrival_date_month'])
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x=fhb['assigned_room_type'])
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x=fhb['customer_type'])
plt.show()

plt.figure(figsize=(100,5))
sns.countplot(x=fhb['country'])
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x=fhb['required_car_parking_spaces'])
plt.show()